# POST http://localhost:3000/signin 
# Content-Type: application/json

# {
    
#     "email": "mahadihasansiam200@outline.com",
#     "password": "Asdvfs553"
    
# }

# access_token - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDZmNzc3ZDljNGFiOTY1NGRmMDFiMCIsImlhdCI6MTcyNTM2NDA4N30.Nco5OkIeLlQ8RRL9pmVlC5u-ND-KTrAnfmPrOpuq5Zk

# POST http://localhost:3000/signup 
#  Content-Type: application/json

#  {
#     "fullname": "siam",
#     "email": "siam1@gmail.com",
#    "password": "Aa@123456"
    
#  }

# GET http://localhost:3000/get-upload-url 
POST http://localhost:3000/create-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZyZXNoZXJ0b29AZ21haWwuY29tIiwiaWF0IjoxNzI0NTI3MDg5LCJleHAiOjE3MjQ2MTM0ODl9.kjIxsVElHNVugoLiQFdJSldp8c2_3DW9pT47wNRQUh4

{
    "title": "this is a test blog1",
    "banner": "https://example.com",
    "des": "this is a short blog1",
    "content": {
        "blocks": [1,2]
    },
    "tags": ["tags1", "tags2"]
}